[profile.default]
src = "contracts/ethereum/src"
out = "contracts/ethereum/out"
libs = ["contracts/ethereum/lib"]
test = "contracts/ethereum/test"
cache_path = "contracts/ethereum/cache"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[rpc_endpoints]
mainnet = "https://eth.merkle.io"
sepolia = "https://eth-sepolia.public.blastapi.io"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }