[package]
name = "AptosEscrow"
version = "1.0.0"
authors = ["Will <will@nospam.com>"]

[addresses]
escrow = "0xad80d336acde3c68e2d92cf4bc81436a624d5626ea67ee363231249becf9f06f"

[dev-addresses]
escrow = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]